openSUSE/kdump

init/mkdumprd, init/setup-kdump.functions
Kdump over ssh failed because missing libnss_files.so required by /etc/nsswitch.conf.
In fact /etc/nsswitch.conf is introduced to support /etc/hosts.  The passwd field is not intended.
So a better fix is leave unnecessary fields out.
=> Fix ssh login failure

init/load.sh
The logic in load.sh will use kexec_load first. If kexec_load fails or
is blocked by kernel, then it will try kexec_load_file on x86_64.
Patch by jlee from SP2 that did not make it to master
=> kdump package should try both kexec_load and kexec_file_load interface (bsc#951144, bsc#1056497)

init/CMakeLists.txt, init/kdump-boot.sh, init/module-setup.sh, init/setup-kdump.functions
The kdump module can be included in the normal (non-kdump) initramfs. It is needed for fadump to work because it uses the normal initramfs to capture the kernel core. In that case some features might interfere with normal boot when kdump is not active. In particular network interfaces only needed for capturing the kernel core need not be initialized in initramfs for normal boot. Also multipath.conf cannot blacklist devices not needed for saving kernel dump during normal boot.
=> Enable kdump features in initramfs only when kdump is active (bsc#1101730)

init/module-setup.sh, init/setup-kdump.functions
Automatically add fence_kdump_send and enable network when the library installed and configured in KDUMP_PRESCRIPT or KDUMP_POSTSCRIPT.
[bsc#1108919](https://bugzilla.suse.com/show_bug.cgi?id=1108919) and [fate#326809](https://fate.suse.com/326809)
Need to explicit configure KDUMP_REQUIRED_PROGRAMS="/usr/lib/fence_kdump_send" and  KDUMP_NETCONFIG="XX:force" to include the library and enable the network.
In SLE11SP4 with mkinitrd, doesn't need this steps.
Include the library when fence-agents installed, enable the network automatically when configure it in PRE/POSTSCRIPT. Keep the consistent steps with SLE11SP4.
=> Add fence_kdump_send automatically when fence-agents installed.

init/load.sh
The noefi and acpi_rsdp can be removed because kernel passes necessary
EFI data for kexec via setup_data since 1fec05336 patch be introduced
in v3.14 kernel. (bsc#1098210)
On the other hand, the MOK (machine owner key) doesn't work with noefi.
It causes that third-party signed kernel modules can not be loaded by
crash kernel. Crash kernel can provide EFI runtime services for loading
MOK after noefi be removed. (bsc#1123940)
The kdump without noefi has been tested on Huawei Kunlun, Intel
minnowboard and KVM-OVMF.
Signed-off-by: Lee, Chun-Yi <jlee@suse.com>
=> Remove noefi and acpi_rsdp for EFI firmware

CMakeLists.txt, init/kdump.service
The kdump udev rule is very broad in scope and may slow down
booting strongly, especially during the coldplug phase where
"add" events for lots of CPU and memory devices have to be
processed. Therefore, activate this rule (which has the purpose
to support real hotplug rather than coldplug) late in the boot
sequence.
=> kdump: activate udev rules late during boot (bsc#1154837)

init/module-setup.sh
Creation of symbolic link to kdump-save.service will fail if the directory doesn't exists, and dump will not be captured because kdump-service.service is never started.
The user will see the rescue mode prompt in this case because systemd will proceed to initrd-switch-root, which will fail (triggering rescue mode) because kdump initrd does not setup /sysroot properly.
See: https://bugzilla.opensuse.org/show_bug.cgi?id=1172670
=> Make sure that initrd.target.wants directory exists (bsc#1172670)

init/load.sh
If kdump is prepared in a dom0, the dom0 kernel cmdline is used
verbatim for the kdump kernel, modulo known-to-be-bad options.
As a result 'console=hvc0' is passed to the kdump kernel.
In a native environment this option causes the kdump kernel to hang,
the system never comes back.
Remove it from the kdump cmdline to make sure the kdump kernel boots.
Signed-off-by: Olaf Hering <olaf@aepfle.de>
=> remove console=hvc0 from commandline

init/load.sh
Busybox logger has no -i option.
=> Drop -i argument from logger

init/setup-kdump.functions
kdump fails to capture the crash because it's unable to mount /dev/root.
if device is /dev/root try to get the correct root device from boot cmdline.
=> setup: consider /dev/root and get it from cmdline

init/setup-kdump.functions
- Make it simpler
- Avoid "evil" bevarior if root has no value
Signed-off-by: Alexandre Vicenzi <alexandre.vicenzi@suse.com>
=> setup: clean kdump_get_root_from_commandline

init/module-setup.sh, kdumptool/routable.cc
Fixes to address problems with DNS resolution of hostnames:
* Avoid an endless loop when resolving a hostname fails with `EAI_AGAIN`.
* Install `/etc/resolv.conf` using its resolved path.
=> Fix DNS resolution of hostnames

init/CMakeLists.txt, init/fadump-module-setup.sh, init/init-fadump.sh, init/mkdumprd
In case of fadump, the initrd image has to be built to boot into the
production environment as well as to offload the active crash dump to
the specified dump target (for boot after crash). As the same image
would be used for both boot scenarios, it could not be built optimally
while accommodating both cases.
Swtich to dracut instead of mkinitrd to build the initrd image. And
use '--include' dracut option to include the initrd image, built for
offloading active crash dump, into the default initrd. Also, introduce
a new out-of-tree dracut module (99zz-fadumpinit) that installs a
customized init program while moving default /init to /init.dracut.
This customized init program is leveraged to isolate fadump image
within the default initrd image by kicking off default boot process
(exec …
=> fadump: isolate fadump initrd image within the default one

init/module-setup.sh
Modules for watchdogs present on the system should be included in the initrd, otherwise the dump may be interrupted by a watchdog.
Add a dependency on the watchdog-modules dracut module.
=> add watchdog modules in initrd

init/unload.sh
Some systems, such as those using secure boot, require the use of
the kexec_file_load syscall instead of kexec_load.
Using kexe -a -p -u will try the new kexec_file_load syscall first,
and if it is not supported, fall back to using the old kexec_load.
=> unload.sh: support kexec unload when kexec_file_load is required

dracut/module-setup.sh
Commit bbe9b1281cd6 ("Do not add  network-related dracut options if
ip= is set explicitly") ensures kdump network-related dracut options
are set according to admin's intention. It relies on KDUMP_COMMANDLINE
& KDUMP_COMMANDLNE_APPEND config options for that. But these options
are currently not applicable for fadump case. Instead, rely on the
parameters passed to the running kernel, as capture kernel boot is
likely to use the same parameters as production kernel for fadump.
Fixes: bbe9b1281cd6 ("Do not add  network-related dracut options if ip= is set explicitly")
Signed-off-by: Hari Bathini <hbathini@linux.ibm.com>
=> Fix network-related dracut options handling for fadump case

doc/implementation/Implementation_Guide.txt, doc/man/mkdumprd.8.txt.in, init/mkdumprd
Currently `mkinitrd` is just a wrapper that internally calls `dracut` and `update-bootloader`.
Since it will be removed in a near future release, it should be replaced. See jsc#PED-265 and bsc#1202443.
PS: maybe adding the `--parallel` option could be considered if messy logs are not a problem (https://github.com/dracutdevs/dracut/commit/6d923262)
=> mkdumprd: replace mkinitrd with native dracut

packaging/suse/kdump.spec
NetworkManager is the default now everywhere going forward (Tumbleweed, MicroOS, ALP) and on ALP, wicked will not even exist.
=> Remove build dependency for wicked

init/kdump.service
kdump needs to run after kdump-early, not before and not simultaneously. In the latter case, one of the kexec_load calls would fail with EBUSY.
=> Run kdump.service only after kdump-early.service is done (boo#1196335)

dracut/setup-kdump.functions
`-n` followed by a variable without quotes always evaluates to true.
E.g.:
```
root=
root=
root=/dev/vda1
```
=> Fix shell condition

doc/man/mkdumprd.8.txt.in, init/mkdumprd
- Add missing `-K <kernel>` and `-I <initrd>` options to mkdumprd help output.
- Add missing `-f` and remove invalid `--help` from man page.
=> mkdumprd: fix help output and man page

sysconfig.kdump.in
By default, use all available CPUs to collect the dump instead of just one CPU. This reduces the dump collection time significantly, specially for the systems with very large memory configuration.
The graph below show the time reduction in dump collection on large memory system from 4 Hours to 10 Minutes.
|
14000   | *
|
|
|
|
|
|
1600   |      *
|
|
1400   |
execution Time (Sec)          |
|
1200   |
|
|
1000   |
|            *
|
800    |
|
|                   *
600    |
|                          *     *
|
------------------------------------
1    9    17    25     33    41
Number of Threads
System details:
Architecture: PowerPC
/proc/vmcore size: 3.7T
Filter level: 1
Similar tests with different filter levels, 31 and 16, also show significant reduction in time consumption for dump …
=> [RFC] sysconfig/kdump: change KDUMP_CPU default value to 0

70-kdump.rules.in
Currently, fadump is re-registered on memory add/remove events. However, with the introduction of the kernel commit c6c5b14dac0d ("powerpc: make fadump resilient with memory add/remove events"), elfcorehdr creation is moved to the second kernel. This makes fadump re-registration on memory add/remove events unnecessary.
To indicate to userspace that the kernel is hotplug ready for the fadump case, a new sysfs entry, /sys/kernel/fadump/hotplug_ready, is introduced. If the hotplug_ready sysfs is set to 1, then there is no need to re-register fadump.
No impact for kernels without /sys/kernel/fadump/hotplug_ready sysfs node.
Relevant kernel commit links:
1. https://msgid.link/20240422195932.1583833-2-sourabhjain@linux.ibm.com
2. https://msgid.link/20240422195932.1583833-3-sourabhjain@linux.ibm. …
=> fadump/udev: Avoid fadump re-registration if kernel is hotplug ready

dracut/module-setup.sh
Commit bbe9b1281cd6 ("Do not add network-related dracut options if ip= is set explicitly") skipped automatic network configuration if the ip= kernel argument was present in KDUMP_COMMANDLINE or KDUMP_COMMANDLINE_APPEND.
Since those options were not available for fadump, commit 61a7cb57b1cd ("Fix network-related dracut options handling for fadump case") used the current kernel parameters instead. So, if the production kernel has an ip= kernel argument, automatic network configuration is skipped for fadump.
However, if the network interface required for accessing the NFS dump target (as configured in KDUMP_SAVEDIR) is not reachable via the ip= configuration, the fadump kernel fails to mount the NFS dump target, and dump collection fails.
Fix this by using FADUMP_COMMANDLINE_APPEND to detect …
=> Fadump: Use FADUMP_COMMANDLINE_APPEND to detect explicit IP configuration
